spring:
  messages:
    basename: messages_ja
    cache-duration: -1
    encoding: UTF-8
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/manager
    username: postgres
    password: postgres

holiday-manager-api:
  base: http://localhost:8082
  endpoint:
    user:
      get-user-list: /user
      get-user: /user/%s
      post-user: /user
      put-user: /user/%s
      delete-user: /user/%s
    group:
      get-group-list: /group
      get-group: /group/%s
      post-group: /group
      put-group: /group/%s
      delete-group: /group/%s
      post-group-members: /group/members
    holiday:
      get-holiday-alert: /holiday/alert/userId/%s
      get-holiday-days: /holiday/days/userId/%s
      post-holiday-grant: /holiday/grant
    holiday-application:
      get-holiday-application: /holiday/application/id/%s
      get-holiday-applications: /holiday/application/applicantId/%s
      get-applying-holiday-applications: /holiday/application/approverId/%s
      post-holiday-apply: /holiday/application/apply
      put-holiday-approve: /holiday/application/approve
      delete-holiday-reject: /holiday/application/reject
      delete-holiday-cancel: /holiday/application/cancel
    holiday-took:
      get-holiday-tooks: /holiday/took/userId/%s
      delete-holiday-took: /holiday/took/userId/%s/eventId/%s
