DROP TABLE IF EXISTS event.event_store CASCADE;

CREATE TABLE event.event_store (
	id bigint generated by default as identity,
	stream_name varchar(36) NOT NULL,
	stream_version integer NOT NULL,
	type varchar(255) NOT NULL,
	payload text NOT NULL,
	created_at timestamp NOT NULL,
	PRIMARY KEY (id)
);
